science/accounts/urls.py
from django.urls import path
from . import views
from .views import logout_user
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('logout', views.logout_user, name='logout'),
    path('edit-profile', views.edit_profile, name='edit_profile')
]

science/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
    path('add/', views.create_article, name='create_article'),
    path('<int:pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:pk>/edit/', views.edit_article, name='edit_article'),
    path('access-denied/', views.access_denied, name='access_denied'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_id>/like/', views.toggle_like, name='toggle_like'),

]

science/main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.about, name='index'),
    path('about', views.about, name='about'),
    path('feedback', views.feedback, name='feedback')
]

science/science/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

science/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db import models
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	def __str__(self):
		return(self.user.username, "profile")
	


from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

class CustomUser(AbstractUser):
    profile_photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)

    # Указание related_name для устранения конфликта
    groups = models.ManyToManyField(
        Group,
        related_name="customuser_set",  # Уникальное имя для обратной ссылки
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="customuser_set",  # Уникальное имя для обратной ссылки
        blank=True
    )

science/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.shortcuts import redirect
from django.contrib.auth import logout

from articles.models import Article
from django import forms
from django.contrib.auth.models import User




class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }


def logout_user(request):
    logout(request)  # Выход пользователя
    return redirect('login')


def login(request):
    if request.method == "POST":
        password = request.POST['password']
        username = request.POST['username']

        user = auth.authenticate(username=username, password = password)
        if user is not None:
            auth.login(request, user)
            return redirect('profile')
        else:
            messages.info(request,'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')



def register(request):

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        c_password = request.POST['c_password']
        username = request.POST['username']
        if password == c_password:
            if User.objects.filter(username = username).exists():
                messages.info(request,'Имя пользователя уже занято')
                return redirect('register')
            elif User.objects.filter(email = email).exists():
                messages.info(request,'Электронное письмо уже отправлено')
                return redirect('register')
            else:
                user =  User.objects.create_user(username = username, password = c_password, email=email, first_name = first_name, last_name= last_name)
                user.save()
                messages.info(request,'Пользователь успешно создан')
                auth.login(request, user)
                return redirect('profile')
        else:
            messages.info(request,'Пароли не совпадают!')
            return redirect('register')
    else:
        return render(request,'accounts/register.html')


@login_required
def profile(request):
    user_articles = Article.objects.filter(author=request.user).order_by('-created_at')  # Получаем статьи текущего пользователя
    return render(request, 'accounts/profile.html', {'user_articles': user_articles})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профиль успешно обновлен!')
            return redirect('profile')  # Имя URL для отображения профиля
    else:
        form = EditProfileForm(instance=request.user)
    
    return render(request, 'accounts/edit_profile.html', {'form': form})


from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

science/accounts/templates/accounts/Shablon.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock %}
    <link rel="stylesheet"  href="{% static 'articles/css/global.css' %} " />
    <script src="{% static 'accounts/Js/globaljs.js' %} "></script>
    <link href="https://fonts.googleapis.com/css2?family=Kodchasan:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Основной фон -->
    <div class="background"></div>

    <!-- Шапка -->
    <header class="header">
        <div class="logo">
            <button class="logo-button">
                <div class="logo-circle"></div>
            </button>
            <span>Rocket Science</span>
        </div>
        <nav class="nav">
            <a href="{% url 'articles:article_list' %}" class="nav-item">Главная</a>
            <a href="{% url 'about' %}" class="nav-item">О нас</a>
            <a href="{% url 'feedback' %}" class="nav-item">Обратная связь</a>
            <a href="{% url 'profile' %}" class="nav-item">Профиль</a>
        </nav>
        <div class="auth-buttons">
            <button class="auth-button" id="memesButton">Коты</button>
                {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="auth-button">Выход</a>
    {% else %}
        <a href="{% url 'login' %}" class="auth-button">Вход</a>
        <a href="{% url 'register' %}" class="auth-button">Регистрация</a>
    {% endif %}
             
        </div>
    </header>

    <!-- Main Content Section -->
    {% block content %}
    {% endblock %}


        <div  id="memesModal" class="memes-modal">
        <div class="memes-modal-content">
            <span class="close-modal">&times;</span>
            <img src="" alt="Случайный мем" class="meme-display">

            </div>
        </div>
    </div>

    <!-- Модальное окно для логотипа -->
    <div id="videoModal" class="video-modal">
        <div class="video-modal-content">
            <span class="close-modal">&times;</span>
            <video id="modalVideo" controls>
                <source src="{% static 'accounts/css/Пробник.mp4' %} " type="video/mp4">
                Ваш браузер не поддерживает видео.
            </video>
        </div>
    </div>

    <!-- Модальное окно для случайного видео -->
    <div id="randomVideoModal" class="video-modal">
        <div class="video-modal-content">
            <span class="close-modal">&times;</span>
            <video id="randomModalVideo" controls>
                <source src="{% static 'accounts/css/Пробник.mp4' %}" type="video/mp4">
                Ваш браузер не поддерживает видео.
            </video>
        </div>
    </div>

    <!-- Футер -->
    <footer class="footer">
        <div class="footer-left">
            <div class="footer-logo">
                <div class="logo-circle"></div>
                <p class="footer-title">Rocket Science</p>
            </div>
        </div>
        <div class="footer-center">
            <p class="footer-contacts">Контакты: +7 779 523 18 44<br>+7 779 523 18 43</p>
            <p class="footer-email">Почта: support@gmail.com<br>support1@gmail.com</p>
        </div>
        <div class="footer-right">© 2024 RocketScience.com</div>
    </footer>

<!-- Передача путей через JSON в скрытый элемент -->
<script id="memes-data" type="application/json">
    [
        "{% static 'accounts/img/кот1.jpg' %}",
        "{% static 'accounts/img/кот2.jpg' %}",
        "{% static 'accounts/img/кот3.jpg' %}",
        "{% static 'accounts/img/кот4.jpg' %}",
        "{% static 'accounts/img/кот5.jpg' %}",
        "{% static 'accounts/img/кот6.jpg' %}",
        "{% static 'accounts/img/кот7.jpg' %}",
        "{% static 'accounts/img/кот8.jpg' %}",
        "{% static 'accounts/img/кот9.jpg' %}",
        "{% static 'accounts/img/кот10.jpg' %}",
        "{% static 'accounts/img/кот11.jpg' %}",
        "{% static 'accounts/img/кот12.jpg' %}",
        "{% static 'accounts/img/кот13.jpg' %}"
    ]
</script>
<script src="{% static 'accounts/js/main.js' %}" defer></script>

   
</body>
</html>

science/accounts/templates/accounts/edit_profile.html
{% extends 'accounts/Shablon.html' %}
{% load static %}
{% block css %}    <link rel="stylesheet" href="{% static 'accounts/css/edit_profile.css' %}">          
{% endblock %}     

{% block content %}
<main class="main-content">
    <div class="frame-inner">
        <h2 class="BigLogin">Редактирование профиля</h2>
        <form id="editProfileForm" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="label" for="first_Name">Имя:</label>
                <input type="text" id="first_Name" class="profile-input input" name="first_name" placeholder="Введите имя" value="{{ form.first_name.value }}" required>
            </div>
            <div class="form-group">
                <label class="label" for="last_Name">Фамилия:</label>
                <input type="text" id="last_Name" class="profile-input input" name="last_name" placeholder="Введите фамилию" value="{{ form.last_name.value }}" required>
            </div>
            <div class="form-group">
                <label class="label" for="email">Почта:</label>
                <input type="email" id="email" class="profile-input input" name="email" placeholder="Введите почту" value="{{ form.email.value }}" required>
            </div>
            <div class="form-group">
                <label class="label" for="username">Псевдоним:</label>
                <input type="text" id="username" class="profile-input input" name="username" placeholder="Введите псевдоним" value="{{ form.username.value }}" required>
            </div>
            <button type="submit" class="button save-button btn btn-primary">Сохранить изменения</button>
            <button type="button" class="button cancel-button">Отмена</button>
        </form>
    </div>
</main>



{% endblock %}

science/accounts/templates/accounts/login.html
{% extends 'accounts/Shablon.html' %}
{% load static %}
{% block css %}    <link rel="stylesheet" href="{% static 'accounts/css/style2.css' %}">
{% endblock %}

    {% block content %}
    <main class="main-content">
        <div class="frame-inner">
            <h1 class="BigLogin">Вход</h1>
            <div class="icons">
                <img class="icon" alt="GitHub" src="{% static 'accounts/img/logo-github.svg' %}">
                <img class="icon" alt="Chrome" src="{% static 'accounts/img/logo-chrome.svg' %}">
                <img class="icon" alt="Google" src="{% static 'accounts/img/logo-google.svg' %}">
            </div>
            <form action="login" method="post">
                 {% csrf_token %}
                <label class="label" for="username">Номер телефона или почта</label>
                <input type="text" id="username" class="input" name="username" placeholder="Введите номер телефона или почту" required>

                <label class="label" for="password">Пароль</label>
                <input type="password" id="password" class="input" name="password" placeholder="Введите пароль" required>

                <a href="#" class="forgotpassword">Забыли пароль?</a>
                <button type="submit" class="button">Вход</button>
            </form>
        </div>
    </main>
{% endblock %}

science/accounts/templates/accounts/profile.html
{% extends 'accounts/Shablon.html' %}
{% load static %}
{% block css %}    <link rel="stylesheet" href="{% static 'accounts/css/profilePage.css' %}">
{% endblock %}


{% block content %}
 <div class="main-content">
  <!-- Профиль пользователя -->
  <div class="profile-container">
    <div class="profile-header">
      <h1>Профиль пользователя</h1>
    </div>
    <div class="profile">
      <div class="profile-photo">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {% if user.profile_photo %}
                    <img src="{{ user.profile_photo.url }}" alt="Фото пользователя" class="profile-photo-img">
                {% else %}
                    <img src="https://via.placeholder.com/150" alt="Фото пользователя" class="profile-photo-img">
                {% endif %}
                <input type="file" name="profile_photo" id="profile_photo" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Загрузить фото</button>
        </form>
    </div>
      <div class="profile-info">
        <h2>{{ user.username }}</h2>
        <p><strong>Имя:</strong> {{ user.first_name }}</p>
        <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
        <p><strong>Почта:</strong> {{ user.email }}</p>
        <p><strong>Псевдоним:</strong> {{ user.username }}</p>
      </div>
    </div>
    <div class="profile-actions">
      <!-- <button class="btn">Редактировать профиль</button> -->
      <form action="{% url 'edit_profile' %}" method="get" style="display: inline;">
        <button type="submit" class="btn btn-warning">Редактировать профиль</button>
      </form>
      <button class="btn">Выход</button>
    </div>
  </div>

  <!-- Секция статей -->
  <div class="post-section">
    <div class="my-articles-section">
      <h2>Мои статьи</h2>
      {% if user_articles %}
      <ul class="articles-list">
        {% for article in user_articles %}
        <li class="article-item">
          <a href="{% url 'articles:article_detail' article.pk %}" class="article-title">{{ article.title }}</a>
          <p class="article-date">Создано: {{ article.created_at|date:"d.m.Y H:i" }}</p>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>У вас пока нет опубликованных статей.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

science/accounts/templates/accounts/register.html
{% extends 'accounts/Shablon.html' %}
{% load static %}
{% block css %}    <link rel="stylesheet" href="{% static 'accounts/css/stylesreg.css' %}">{% endblock %}

    {% block content %}
    <div class="registration-container">
        <div class="registration-form">
            <h2>Регистрация</h2>
            <form action="register" method ="post">
                {% csrf_token %}
                <div class="form-row">
                    <label for="first-name">Имя</label>
                    <input type="text" id="first-name" name="first_name" required>
                    <label for="last-name">Фамилия</label>
                    <input type="text" name="last_name" placeholder="last name" required>
                </div>
                <label for="email">Почта</label>
                <input type="email" name="email" placeholder="email" required>
                <label for="username">Псевдоним</label>
                <input type="text" id="username" name="username" required>
                <label for="password">Пароль</label>
                <input type="password" name="password" placeholder="Password" required>
                <label for="confirm-password">Повторите пароль</label>
                <input type="password" name="c_password" placeholder="Confirm Password">
                <input type="submit" name="submit" class="register-button">Регистрация</input>
            </form>
        </div>
        </div>
    {% endblock %}  
        